---
- name: Install docker to raspi
  hosts: all
  tasks:
    - name: Install dependencies
      ansible.builtin.apt:
        name: "{{ item }}"
        state: present
        update_cache: true
      loop:
        - apt-transport-https
        - ca-certificates
        - curl
        - gnupg-agent
        - software-properties-common
    - name: Add GPG key
      ansible.builtin.shell: |
        install -m 0755 -d /etc/apt/keyrings
        set -o pipefail && curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo gpg --dearmor -o /etc/apt/keyrings/docker.gpg
        chmod a+r /etc/apt/keyrings/docker.gpg
      changed_when: false
    - name: Add docker repository to apt
      ansible.builtin.apt_repository:
        repo: deb https://download.docker.com/linux/{{ ansible_distribution | lower }} {{ ansible_distribution_release | lower }} stable
        state: present
    - name: Install docker
      ansible.builtin.apt:
        name: "{{ item }}"
        update_cache: true
      loop:
        - docker-ce
        - docker-ce-cli
        - containerd.io
        - docker-buildx-plugin
        - docker-compose-plugin
    - name: Check docker is active
      ansible.builtin.service:
        name: docker
        state: started
        enabled: true
    - name: Ensure group "docker" exists
      ansible.builtin.group:
        name: docker
        state: present
    - name: Join to the swarm
      ansible.builtin.command: docker swarm join --token \
        SWMTKN-1-3ffppcelrodzzq0lxk6ls94dgninmy4ra9t2xvr8v67nh2k6n1-9txhrzj1xoko3lx3fbigdjtgc 192.168.1.211:2377
      changed_when: false
