---
- name: Install docker to raspi
  hosts: all
  tasks:
    - name: Install dependencies
      ansible.builtin.apt:
        name: "{{ item }}"
        state: present
        update_cache: true
      loop:
        - apt-transport-https
        - ca-certificates
        - curl
        - gnupg-agent
        - software-properties-common
    # problema ad eseguire questo task sia su ubuntu che su raspian
    # - name: Add GPG key
    #   ansible.builtin.shell: |
    #     install -m 0755 -d /etc/apt/keyrings
    #     rm /etc/apt/keyrings/docker.gpg
    #     set -o pipefail && curl -fsSL https://download.docker.com/linux/{{ ansible_release | lower }}/gpg | gpg --dearmor -o /etc/apt/keyrings/docker.gpg
    #     chmod a+r /etc/apt/keyrings/docker.gpg
    #   args:
    #     executable: /usr/bin/bash
    #   changed_when: false
    - name: Install docker
      ansible.builtin.apt:
        name: "{{ item }}"
        update_cache: true
      loop:
        - docker-ce
        - docker-ce-cli
        - containerd.io
        - docker-buildx-plugin
        - docker-compose-plugin
    - name: Check docker is active
      ansible.builtin.service:
        name: docker
        state: started
        enabled: true
    - name: Ensure group "docker" exists
      ansible.builtin.group:
        name: docker
        state: present
